### ISSUE TITLE
Monitor name regexp and REST API URL

### ISSUE THREAD

**Issue by compunova** [waynieack/HikvisionZM#1]
Wayne, thanks for putting together this nice script! I'm working with it now. Two issues that I found: I have interpreted this "_mol-" to be a substring, though within the code it's actually confirms your example that it requires it to be at the end. So I changed the script to search it as a substring so that I could use it as "hik_mol-01".

Second one was ISAPI in the REST API path. It turned out that it's not required on my camera, and I get "connection reset by peer" if I use it. So I had to remove ISAPI from the two places it's used in the code.

In the next couple of days I'll be testing it with two cameras, so I'll let you know about the multithreaded support that you have added.

PS: Hit me up on Skype if you'd like, will be glad to give you details as I go.

**Comment by waynieack** [comment]
Sorry, I missed the notification of your message. I know its been a long time, but thank you for your comments. 

I updated the script to make the /ISAPI part of the URL optional, I guess they changed the API at some point in the code versions. You can now just remove it at the top of the script if needed. 

I also removed the "$" anchor from the search string so you can make the search string any part of the camera name and not just a suffix. 

I assume that the multiple cameras worked for you, I just purchased a second camera a few months ago and its working perfectly. It has a built in PIR motion detector and I have added that alarm type as well. 

Let me know if the new version of the code works for you.

-Wayne
