### ISSUE TITLE
Help configuring script

### ISSUE THREAD

**Issue by josh4trunks** [waynieack/HikvisionZM#2]
Hello, thank you for your work on this program! I am starting this script fine, but it seems to not be receiving PIR events from my Hikvision 2432 camera. I know the camera is triggering its own events as verified by the "Audible Warning", but I'm not sure if the camera is proving the needed XML.
When I `curl -s -S -N -u zmuser:zmpass http://192.168.1.45/ISAPI/Event/notification/alertStream` I get the following which keeps updating.

```
--boundary
Content-Type: application/xml; charset="UTF-8"
Content-Length: 480

<EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<ipAddress>192.168.1.45</ipAddress>
<portNo>80</portNo>
<protocol>HTTP</protocol>
<macAddress>28:58:be:6e:53:0c</macAddress>
<channelID>1</channelID>
<dateTime>2016-07-19T19:24:46--8:00</dateTime>
<activePostCount>0</activePostCount>
<eventType>videoloss</eventType>
<eventState>inactive</eventState>
<eventDescription>videoloss alarm</eventDescription>
</EventNotificationAlert>
--boundary
Content-Type: application/xml; charset="UTF-8"
Content-Length: 480

<EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<ipAddress>192.168.1.45</ipAddress>
<portNo>80</portNo>
<protocol>HTTP</protocol>
<macAddress>28:58:be:6e:53:0c</macAddress>
<channelID>1</channelID>
<dateTime>2016-07-19T19:24:46--8:00</dateTime>
<activePostCount>0</activePostCount>
<eventType>videoloss</eventType>
<eventState>inactive</eventState>
<eventDescription>videoloss alarm</eventDescription>
</EventNotificationAlert>
```

Here are my camera settings.
![screenshot from 2016-07-19 19-26-44](https://cloud.githubusercontent.com/assets/1018807/16973207/c315ec64-4de6-11e6-8140-2c421c4aba9d.png)

**Any suggestions?**

**Comment by josh4trunks** [comment]
Ohh, and just to make sure you get a direct ping @waynieack

**Comment by waynieack** [comment]
The video loss message is the normal message you will get when nothing has
been triggerd on the camera, but when you make movement in front of the
camera for PIR, you should see that change to PIR in the eventtype field of
the xml message. You will see the message change for a short period so you
will need the computer near the camera or a second person.

As for the settings on the camera, all I have on my cameras is the enable
PIR checked and the schedule enabled like you do below. The other settings
didnt matter if they were enabled or disabled.

Are you not seeing the event type message change in the xml stream when the
PIR is triggered?

**Comment by josh4trunks** [comment]
I don't even see the PIR eventType in my xml message. Above is exactly what I see when I use curl to fetch the URL, but repeatedly until I stop the curl command.

Do you think my output is getting cut off in curl and your script at the "--boundary". Gonna experiment with some other programs that pull from hikvision camera's alertStream to verify if they have the same issue.

**Comment by waynieack** [comment]
Yeah, the stream continuously sends the video loss XML until another event
is triggered. My script connects to that exact stream that you are seeing
and waits for a message other than the video loss message. If you aren't
seeing it then the script will not either. Have you tried some of the other
alarm types like motion detection?

It sounds like a bug with the camera, try unchecking all the
Linkage Methods just to see if it helps and/or rebooting the camera.

Maybe try changing the schedule and chaining it back, the schedule is the
only thing (other than the enable check) that I've seen stop the messages
on my cameras.

I have these 2 cameras and they send the events ok, if i do a curl on the
stream i see the XML change when I move in front of the camera.

Model     DS-2CD2432F-IW
Firmware Version     V5.3.0 build 151016

Model     DS-2CD2332-I
Firmware Version     V5.2.5 build 141201

**Comment by josh4trunks** [comment]
ok, sounds good. I'll try motion detection / and adjusting schedules / rebooting.
I have the 2432 with the 5.2.5 firmware, so I guess I could try updating the firmware to 5.3.0 if none of he above work.
Thanks!

**Comment by josh4trunks** [comment]
well the motion and the line detection do show on the stream. But the PIR still does not.
Gonna try 5.3.0, but I can't download it from Hikvision's site yet since I need to register there and their activation email isn't instant.

Know anyplace else I can get the latest firmware?

**Comment by josh4trunks** [comment]
Well in the process of trying to upgrade my unit 2432 to v5.3.0 it got bricked.
I should have realized something was fishy, the sticker on the device says 5.3.0 while the web-interface said 5.2.5, so I suspect it was hacked english firmware.

Now gotta get it working again =/

**Comment by josh4trunks** [comment]
well got my unit unbricked using this post! now back to the issue at hand.
https://www.ipcamtalk.com/showthread.php/3408-HIKVISION-mtd-Brick-Recovery-Guide?p=113233&viewfull=1#post113233

my unit does not seem to output anything related to PIR to the alertStreaming stream. do you mind posting the output you get when your PIR triggers an event. I'm able to query it at a different URL, but don't get anything from the stream.

**Comment by josh4trunks** [comment]
specifically, I was able to connect to the URL listed here..
https://community.openhab.org/t/hikvision-event/8736/3

**Comment by waynieack** [comment]
This is how I have mine configured.

[image: Inline image 1]

On the http stream, I see this when the PIR is triggered.

<EventNotificationAlert version="2.0" xmlns="
http://www.hikvision.com/ver20/XMLSchema">
<ipAddress>192.168.195.56</ipAddress>
<portNo>80</portNo>
<protocol>HTTP</protocol>
<macAddress>bc:ad:28:38:92:1f</macAddress>
<channelID>1</channelID>
<dateTime>2016-07-22T08:11:44-6:00</dateTime>
<activePostCount>5</activePostCount>
<eventType>PIR</eventType>
<eventState>active</eventState>
<eventDescription>PIR alarm</eventDescription>
</EventNotificationAlert>
--boundary
Content-Type: application/xml; charset="UTF-8"
Content-Length: 467

As for the /IO/outputs/1/status, its not an http stream so it would not
work in the way that I am pulling the events. I make a connection and it
stays open watching for new events, the /IO/outputs/1/status URL would have
to be polled constantly which would be resource intensive to open and close
connections like that.

I tried linking my PIR event to the alarm output, but I don't see the
output pushing events to the HTTP stream when motion is detected. Also I
noticed that when I check the trigger alarm output check box, it no longer
sends the PIR events to the HTTP stream, so apparently some of the linkages
break the HTTP push notifications.

_Wayne

**Comment by josh4trunks** [comment]
Yeah, I realize the IO URL isn't the same. No idea why my thing isn't working =[
For some reason I don't see the image you posted. Also what's the curl command you are using?

I'll check on the ipcamtalk forum, maybe I do need to get to V5.3.0 without bricking it.

**Comment by waynieack** [comment]
curl http://user:password@192.168.1.1/ISAPI/Event/notification/alertStream

If you see the stream, then your curl command is fine. The problem is for
sure with the camera.

**Comment by josh4trunks** [comment]
Alright it was an issue with the firmware that was hacked on their. Hacked the camera partitions and put back the 5.3.0 chinese firmware and PIR events are now working. Excited to try out your script

**Comment by josh4trunks** [comment]
By the way, the script works great on my FreeBSD system, connected to my Hikvision 2432 with the original Chinese firmware using the PIR sensor =]

This will be even more awesome once Zoneminder has video support, so my server won't need to use CPU converting the video stream  to JPEGs or analysing it!

**Comment by waynieack** [comment]
Glad to hear it!

_Wayne
