### ISSUE TITLE
Support for ffmpeg camera configuration

### ISSUE THREAD

**Issue by jshank** [waynieack/HikvisionZM#3]
Awesome script, it's working for me after a little hacking. The H.264 supported method for configuring these cameras is to [use ffmpeg](https://wiki.zoneminder.com/Hikvision). Unfortunately this populates the `Path` field instead of the `Host` field with the camera credentials in the `Monitors` table. It's also a different format than the script is expecting. 

I noticed if I switched to remote as suggested, the script worked but I could no longer see video. However, when I switched back to ffmpeg, the script still worked! Looking deeper in the database, ZM appears to leave the configuration in the `Host` field even though it switches the `type` back to `Ffmpeg` . I went into the database and ran `select Host,Path,Id,Name,Function from Monitors where find_in_set( Function, 'Modect,Record,Nodect,Mocord' );` I then manually updated each `Host` field to include the scripts preferred format `user:password@ipaddress` (hostnames don't work). `update Monitors set Host = 'user:pass@192.168.1.1' where Id  = 10;` The Id comes from your previous query.

**Comment by waynieack** [comment]
OK, so I could check to see if ffmpeg is selected and pull the
user/pass/host from the Path field. Is all the information in the path
field when using ffmpeg in the same format as remote (user:pass@IPaddress)?

I'll look into the hostname issue, I don't see why it wouldn't work now.

_Wayne

**Comment by jshank** [comment]
Here is the format of the Path field:
`rtsp://username:password@hostname.domain.tld:554/Streaming/Channels/1`

**Comment by waynieack** [comment]
ok, that will work.

Its odd that it does not work with remote, I have 2 cameras and they both
work using the remote format.

**Comment by waynieack** [comment]
The latest code should work with the ffmpeg paths with out modifying the database. Please pull the new code and let me know if you have any issues.
