### ISSUE TITLE
Problem with v1.32.3 

### ISSUE THREAD

**Issue by theuserz** [waynieack/HikvisionZM#5]
I have got following errors when events occurs with Zoneminder  v1.32.3:

ERR [ZoneMinder::Memory::Mapped:150] [Can't read from mapped memory for monitor '6', gone away?]
ERR [ZoneMinder::Memory::Mapped:150] [Can't read from mapped memory for monitor '6', gone away?]
Some perl libs in v1.32  are broken now?

**Comment by waynieack** [comment]
Grab the new version I just pushed, it should fix the issue.

**Comment by theuserz** [comment]
Thank you very much! Fixed!
